"""Criação inicial das tabelas

Revision ID: 090dec7bd1a6
Revises: 
Create Date: 2025-05-15 17:24:55.669755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '090dec7bd1a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recibos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recibos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sessoes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_pago', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('numero_recibo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gerado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='recibos_pkey'),
    sa.UniqueConstraint('numero_recibo', name='recibos_numero_recibo_key')
    )
    # ### end Alembic commands ###
