"""criar todas as tabelas

Revision ID: 24c6ced0f9e4
Revises: 
Create Date: 2025-06-03 11:35:29.657682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c6ced0f9e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_emergencia', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('repeticao_id', sa.String(length=36), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo_atendimento', sa.String(length=30), nullable=False),
    sa.Column('frequencia', sa.String(length=20), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('foi_realizada', sa.Boolean(), nullable=True),
    sa.Column('foi_paga', sa.Boolean(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('sessoes')
    op.drop_table('historicos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
